---
abstract: "Use 'unknown' values instead of undef ones"
author:
  - "Curtis \"Ovid\" Poe <ovid@cpan.org>"
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: unknown
resources:
  repository: git://github.com/Ovid/unknown.git
version: 0.001
